# 需要修改为.json后缀
# {
#   "token_secret": "long-secret",
#   "db": {
#     "host": "localhost",
#     "port": 5432,
#     "username": "toimc",
#     "password": "example"
#   }
# }
token_secret: long-secret
db:
  host: "localhost"
  port: 5432
